# Introduction to Data Science
## Homework 2

Student Name: 
Muhe Xie

### Part 1: Case study
- Read [this article](http://www.nytimes.com/2012/02/19/magazine/shopping-habits.html) in the New York Times
- Use what we've learned in class as well as from the book and our readings to describe how one could set this up as a predictive modeling problem, such that they could have gotten the results that they did

### Answer
- #### 1 Identify the business question: 
Build a predictive model and use the model to predict that how likely an individual is pregnant, more specifically, to predict that how likely an individual is in her second trimester during which they are more likely to buy new things. 
The response will be 0 (not in this pregnant stage) or 1 (in  this pregnant stage). And we need to calculate the probability of this binary response. Many algorithms can be used, like Logistic Regression, Naive Bayes, SVM, etc.
- #### 2 Data understanding and preparation:
First we need to know which data source we can utilize. In this case, we can use the customer database of Target Company and questionnaires if possible. We can obtain the information about customer's gender, age, address, shopping history (time, frequency and purchased items), salary, pregnancy information (if possible by questionaire), changes in shopping habits (will probably occur when some one is pregnant).
- #### 3 Modeling:
After initial analysis of the data, we can choose an appropriate model. This is the stage where skills of data mining play an important role. We use mathematical skills to study the problem, the input will be variable data related with customers, the output will be the probability of the pregnancy. After that we can use the training data to train the model to get the estimated parameters for the model.
- #### 4 Evaluation: 
To evaluate the accuracy of the model, we need the test data (which is hard to obtain in this case since it is not easy for us to get the accurate information of whether one is pregnant or which stage of pregnancy she is in). We can also use the data of whether a customer purchases pregnancy related goods after Target have sent the coupons to her. Lab tests might also be used but will probably not be reliable enough considering the complex business context.
- #### 5 Deployment:
After the model is validated, Target can use the data to calculate the probability of a specific costomer being in her second trimester. And then send advertisements and coupons of corresponding products to her, like maternity clothing and prenatal vitamins. And we can get the results from the sales data.

### Part 2: Exploring data in the command line
For this part we will be using the data file located in `"data/advertising_events.csv"`. This file consists of records that pertain to some advertising events on a given day. There are 4 comma separated columns in this order: `userid`, `timestamp`, `domain`, and `action`. These fields are of type `int`, `int`, `string`, and `int` respectively. Answer the following questions using Linux/Unix bash commands. All questions can be answered in one line (sometimes, with pipes)! Some questions will have many possible solutions. Don't forget that in IPython notebooks you must prefix all bash commands with an exclamation point, i.e. `"!command arguments"`.

1\. How many records are in this file?

In [1]:
!wc -l ./advertising_events.csv

   10341 ./advertising_events.csv

2\. How many unique users are in this file?

In [2]:
!cat ./advertising_events.csv|cut -d $',' -f 1|sort|uniq -c|wc -l

     732

3\. Rank all domains by the number of visits they received in descending order.

In [3]:
!cat ./advertising_events.csv|cut -d $',' -f 3 | sort | uniq -c |sort -r -t $' ' -k 1 -n

3114 google.com
2092 facebook.com
1036 youtube.com
1034 yahoo.com
1022 baidu.com
 513 wikipedia.org
 511 amazon.com
 382 qq.com
 321 twitter.com
 316 taobao.com

4\. List all records for the user with user id 37.

In [4]:
!grep '^37,' advertising_events.csv

37,648061658,google.com,0
37,642479972,google.com,2
37,644493341,facebook.com,2
37,654941318,facebook.com,1
37,649979874,baidu.com,1
37,653061949,yahoo.com,1
37,655020469,google.com,3
37,640878012,amazon.com,0
37,659864136,youtube.com,1
37,640361378,yahoo.com,1
37,653862134,facebook.com,0
37,648828970,youtube.com,0

### Part 3: Dealing with messy data
Not all data you will deal with is going to be clean. In fact, much of it will be very messy! For example, we have the HTML page that lists the contributors to Facebook's [osquery](https://github.com/facebook/osquery) project that is hosted on [Github.com](https://github.com). In this case, all we are interested in are the contributors and how many commits each of them has. Given the HTML page in `"data/osquery_contributors.html"` you will sift through tons of irrelevant data so that you can build a useful data structure.

Notice that the first six (out of 59 total) contributors are named "theopolis", "marpaia", "javuto", "jedi22", "unixist", and "mofarrell". They have 553, 477, 104, 49, 30, 25 commits respectively.

![Screenshot](images/osquery_contributors.png)

To get a better of understanding of how this data is stored in the file, try searching through the raw data file for these usernames to look for any patterns. Your final dictionary should have 59 elements!

1\. Turn this data into a Python dictionary called `contributors` where the keys are the contributor names and the values are the number of commits that each contributor has.

In [5]:
import re # you might find this package useful

contributors = dict()

str = 'a class="aname" href="/'  # line starts with this string contains name
txt = open ("./osquery_contributors.html")
lists = [] # lists of lines which contains name information of contributors
commit_line_lists = [] # lists of lines which contains number of commits
filelines = txt.readlines()

for i in range(len(filelines)): # read file line by line and add the required ones in the two lists
    if str in filelines[i]:
        lists.append(filelines[i])
        commit_line_lists.append(filelines[i+3]) # line of commit information are 3 lines below the name line
        
namelists = [] # lists of name string 
numberlists = [] # lists of number of commits string 

for i in range(59): # extract the name in the line
    for j in range(24,len(lists[i])): # start searching the string for name, character by character
        if lists[i][j] == "\"":  # end symbol
            name_in_this = lists[i][24:j]
            namelists.append(name_in_this)
            
for i in range(59): # extract the commit times in the line
    for j in range(74+len(namelists[i]),len(commit_line_lists[i])): # start searching the string for name
        if commit_line_lists[i][j] == " ": # end symbol
            number_in_this = commit_line_lists[i][(74+len(namelists[i])):j]
            numberlists.append(number_in_this)
            
for i in range(59): # add to the dict
    contributors[namelists[i]] = int(numberlists[i])

            
# This line will print your dictionary for grading purposed. Do not remove this line!!!
print contributors

{'shawndavenport': 1, 'jedi22': 49, 'schettino72': 2, 'jamesgpearce': 2, 'marpaia': 477, 'wxsBSD': 20, 'blakefrantz': 6, 'yetanotherhacker': 1, 'lwhsu': 22, 'mimeframe': 3, 'd0ugal': 1, 'maus-': 9, 'kost': 1, 'polachok': 14, 'achmiel': 3, 'vmauge': 8, 'theopolis': 553, 'yannick': 1, 'stevenhilder': 1, 'SimplyAhmazing': 1, 'timzimmermann': 2, 'mark-ignacio': 1, 'mgoffin': 2, 'deniszh': 3, 'Anubisss': 2, 'vlajos': 1, 'dreid': 1, 'astanway': 6, 'arubdesu': 1, 'sharvilshah': 23, 'jreese': 2, 'justintime32': 1, 'nlsun': 3, 'mathieuk': 2, 'ecin': 1, 'blackfist': 1, 'apage43': 1, 'zwass': 14, 'mofarrell': 25, 'maclennann': 6, 'quad': 1, 'arirubinstein': 4, 'brandt': 3, 'rjeczalik': 1, 'ga2arch': 2, 'mtmcgrew': 1, 'alex': 1, 'unixist': 30, 'cdown': 4, 'javuto': 104, 'larzconwell': 1, 'castrapel': 2, 'jacknagz': 1, 'akshaydixi': 5, 'mlw': 2, 'glensc': 2, 'tburgin': 1, 'DavidGosselin': 1, 'eastebry': 9}

### Part 4: Dealing with data Pythonically

In [6]:
# You might find these packages useful. You may import any other you want!
import pandas as pd
import numpy as np

1\. Download the data set `"data/ads_dataset.tsv"` and load it into a Python Pandas data frame called `ads`.

In [7]:
# Place your code here
from pandas import Series, DataFrame 
ads = pd.read_table('./ads_dataset.tsv',sep = '\t')
ads.index = range(0,54584)
ads

,isbuyer,buy_freq,visit_freq,buy_interval,sv_interval,expected_time_buy,expected_time_visit,last_buy,last_visit,multiple_buy,multiple_visit,uniq_urls,num_checkins,y_buy
0,0,NaN,1,0,0.000000,0,0.000000,106,106,0,0,169,2130,0
1,0,NaN,1,0,0.000000,0,0.000000,72,72,0,0,154,1100,0
2,0,NaN,1,0,0.000000,0,0.000000,5,5,0,0,4,12,0
3,0,NaN,1,0,0.000000,0,0.000000,6,6,0,0,150,539,0
4,0,NaN,2,0,0.500000,0,-101.149300,101,101,0,1,103,362,0
5,0,NaN,1,0,0.000000,0,0.000000,42,42,0,0,17,35,0
6,0,NaN,1,0,0.000000,0,0.000000,42,42,0,0,42,110,0
7,0,NaN,2,0,29.791670,0,-106.188300,121,121,0,1,101,401,0
8,0,NaN,3,0,45.479170,0,-34.144730,64,64,0,1,100,298,0
9,0,NaN,1,0,0.000000,0,0.000000,13,13,0,0,53,247,0
10,1,1,2,0,0.958333,0,-20.671200,21,21,0,1,65,175,0
11,0,NaN,2,0,21.333330,0,-108.323000,118,118,0,1,163,891,0
12,0,NaN,1,0,0.000000,0,0.000000,151,151,0,0,24,198,0
13,0,NaN,1,0,0.000000,0,0.000000,19,19,0,0,16,48,0
14,0,NaN,1,0,0.000000,0,0.000000,81,81,0,0,32,177,0
15,0,NaN,1,0,0.000000,0,0.000000,68,68,0,0,64,305,0
16,0,NaN,1,0,0.000000,0,0.000000,36,36,0,0,76,163,0
17,0,NaN,2,0,15.958330,0,-6.683471,14,14,0,1,101,1105,0
18,0,NaN,1,0,0.000000,0,0.000000,19,19,0,0,30,76,0
19,0,NaN,1,0,0.000000,0,0.000000,70,70,0,0,168,1317,0
20,0,NaN,2,0,27.250000,0,-124.610000,138,138,0,1,172,828,0
21,0,NaN,2,0,133.125000,0,50.474090,16,16,0,1,67,396,0
22,0,NaN,3,0,8.395833,0,2.534722,3,3,0,1,146,398,0
23,0,NaN,1,0,0.000000,0,0.000000,9,9,0,0,-1,26,0
24,0,NaN,1,0,0.000000,0,0.000000,145,145,0,0,179,1215,0
25,0,NaN,8,0,15.994050,0,12.569260,1,1,0,1,64,167,0
26,0,NaN,1,0,0.000000,0,0.000000,39,39,0,0,165,3883,0
27,0,NaN,1,0,0.000000,0,0.000000,34,34,0,0,96,219,0
28,0,NaN,1,0,0.000000,0,0.000000,135,135,0,0,143,1011,0
29,0,NaN,1,0,0.000000,0,0.000000,77,77,0,0,81,219,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54554,0,NaN,1,0,0.000000,0,0.000000,6,6,0,0,0,182,0
54555,0,NaN,1,0,0.000000,0,0.000000,44,44,0,0,84,139,0
54556,0,NaN,1,0,0.000000,0,0.000000,85,85,0,0,169,276,0
54557,0,NaN,1,0,0.000000,0,0.000000,49,49,0,0,18,45,0
54558,0,NaN,1,0,0.000000,0,0.000000,30,30,0,0,53,506,0
54559,0,NaN,1,0,0.000000,0,0.000000,10,10,0,0,109,1131,0
54560,0,NaN,1,0,0.000000,0,0.000000,77,77,0,0,11,38,0
54561,0,NaN,1,0,0.000000,0,0.000000,14,14,0,0,9,87,0
54562,0,NaN,3,0,28.229170,0,-7.932672,26,26,0,1,162,1178,0
54563,0,NaN,1,0,0.000000,0,0.000000,48,48,0,0,39,139,0
54564,0,NaN,1,0,0.000000,0,0.000000,38,38,0,0,26,117,0
54565,0,NaN,1,0,0.000000,0,0.000000,70,70,0,0,171,506,0
54566,0,NaN,2,0,8.541667,0,-14.237070,18,18,0,1,-1,3,0
54567,0,NaN,1,0,0.000000,0,0.000000,71,71,0,0,63,254,0
54568,0,NaN,1,0,0.000000,0,0.000000,185,185,0,0,184,1358,0
54569,0,NaN,1,0,0.000000,0,0.000000,95,95,0,0,164,2462,0
54570,0,NaN,1,0,0.000000,0,0.000000,134,134,0,0,174,499,0
54571,0,NaN,10,0,7.101852,0,3.137754,3,3,0,1,103,255,0
54572,0,NaN,1,0,0.000000,0,0.000000,109,109,0,0,143,808,0
54573,0,NaN,1,0,0.000000,0,0.000000,57,57,0,0,164,1912,0
54574,0,NaN,2,0,131.083300,0,34.678500,30,30,0,1,30,214,0
54575,0,NaN,1,0,0.000000,0,0.000000,181,181,0,0,22,125,0
54576,0,NaN,1,0,0.000000,0,0.000000,69,69,0,0,95,187,0
54577,0,NaN,1,0,0.000000,0,0.000000,119,119,0,0,103,1338,0
54578,0,NaN,1,0,0.000000,0,0.000000,37,37,0,0,1,22,0
54579,0,NaN,3,0,30.979170,0,12.621240,8,8,0,1,168,2080,0
54580,0,NaN,2,0,1.041667,0,-0.916713,1,1,0,1,1,15,0
54581,0,NaN,1,0,0.000000,0,0.000000,20,20,0,0,132,556,0
54582,0,NaN,1,0,0.000000,0,0.000000,180,180,0,0,71,400,0
54583,0,NaN,1,0,0.000000,0,0.000000,185,185,0,0,77,401,0

2\. Write a Python function called `getDfSummary()` that does the following:
- Takes as input a data frame
- For each variable in the data frame calculates the following features:
  - `number_nan` to count the number of missing not-a-number values
  - Ignoring missing, NA, and Null values:
    - `number_distinct` to count the number of distinct values a variable can take on
    - `mean`, `max`, `min`, `std` (standard deviation), and `25%`, `50%`, `75%` to correspond to the appropriate percentiles
- All of these new features should be loaded in a new data frame. Each row of the data frame should be a variable from the input data frame, and the columns should be the new summary features.
- Returns this new data frame containing all of the summary information

Hint: The pandas `describe()` method returns a useful series of values that can be used here.

In [8]:
def getDfSummary(input_data):
    
    base_frame = input_data.describe() # the result will do some modification based on the result of ads.describe function
    addtional_frame =DataFrame(columns = base_frame.columns,index = ['number_nan','number_distinct']) #creat a new frame contain the number_nan and number_distiinct 
    for column_member in input_data.columns: # calculate the new frame 
        addtional_frame.ix['number_nan',column_member] = sum(input_data[column_member].isnull())
        addtional_frame.ix['number_distinct',column_member] = len(input_data[column_member].dropna().unique())
    base_frame = base_frame.drop('count') # do not need this statistical 
    output_data = pd.concat([addtional_frame,base_frame])
    output_data = output_data.T
    
    return output_data

getDfSummary(ads)

,number_nan,number_distinct,mean,std,min,25%,50%,75%,max
isbuyer,0,2,0.04263154,0.2020268,0,0,0,0,1
buy_freq,52257,10,1.240653,0.782228,1,1,1,1,15
visit_freq,0,64,1.852777,2.92182,0,1,1,2,84
buy_interval,0,295,0.2100077,3.922016,0,0,0,0,174.625
sv_interval,0,5886,5.82561,17.59544,0,0,0,0.1041667,184.9167
expected_time_buy,0,348,-0.1980401,4.997792,-181.9238,0,0,0,84.28571
expected_time_visit,0,15135,-10.21079,31.87972,-187.6156,0,0,0,91.40192
last_buy,0,189,64.72933,53.47666,0,18,51,105,188
last_visit,0,189,64.72933,53.47666,0,18,51,105,188
multiple_buy,0,2,0.006357174,0.07947878,0,0,0,0,1
multiple_visit,0,2,0.2774439,0.4477415,0,0,0,1,1
uniq_urls,0,207,86.56934,61.96976,-1,30,75,155,206
num_checkins,0,4628,720.6576,1275.727,1,127,319,802,37091
y_buy,0,2,0.004635058,0.06792392,0,0,0,0,1

3\. How long does it take for your `getDfSummary()` function to work on your `ads` data frame? Show us the results below.

Hint: `%timeit getDfSummary(ads)`

In [9]:
# Place your code here
%timeit getDfSummary(ads)
# 1 loops, best of 3: 1.12 s per loop

1 loops, best of 3: 1.1 s per loop

4\. Using the results returned from `getDfSummary()`, which fields, if any, contain missing `NaN` values?

In [10]:
# Place your code here
results = getDfSummary(ads)
for variable in results.index:
    if results.ix[variable,'number_nan'] >0:
        print variable
# As the result shows, buy_freq contains missing NaN values.

buy_freq

5\. For the fields with missing values, does it look like the data is missing at random? Are there any other fields that correlate perfectly, or predict that the data is missing? If missing, what should the data value be?

Hint: create another data frame that has just the records with a missing value. Get a summary of this data frame using `getDfSummary()` and compare the differences. Do some feature distributions change dramatically?

In [11]:
# Place your code here
frame_missing_data = ads
for index_member in frame_missing_data.index:
    if pd.isnull(frame_missing_data.ix[index_member,'buy_freq']) == False: # this line is not missing, drop it
        frame_missing_data = frame_missing_data.drop([index_member])
getDfSummary(frame_missing_data)

# I find that variable isbuyer is related with the buy-freq, isbuyer is always 0 when buy_freq data is missing, 
# and at the same time buy_interval, expected_time_buy, multiple_buy is also always 0

,number_nan,number_distinct,mean,std,min,25%,50%,75%,max
isbuyer,0,1,0,0,0,0,0,0,0
buy_freq,52257,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
visit_freq,0,48,1.651549,2.147955,1,1,1,2,84
buy_interval,0,1,0,0,0,0,0,0,0
sv_interval,0,5112,5.686388,17.62356,0,0,0,0.0416667,184.9167
expected_time_buy,0,1,0,0,0,0,0,0,0
expected_time_visit,0,13351,-9.669298,31.23903,-187.6156,0,0,0,91.40192
last_buy,0,189,65.74132,53.48462,0,19,52,106,188
last_visit,0,189,65.74132,53.48462,0,19,52,106,188
multiple_buy,0,1,0,0,0,0,0,0,0
multiple_visit,0,2,0.2556021,0.4362033,0,0,0,1,1
uniq_urls,0,207,86.65618,61.99671,-1,30,75,155,206
num_checkins,0,4570,721.8485,1284.504,1,126,318,803,37091
y_buy,0,2,0.003023518,0.05490387,0,0,0,0,1

6\. Which variables are binary?

In [12]:
# Place your code here
results = getDfSummary(ads)
for variable in results.index:
    if  results.ix[variable,'number_distinct'] == 2:
        print variable
# isbuyer, multiple_buy, multiple_visit, y_buy

isbuyer
multiple_buy
multiple_visit
y_buy

7\. Generate a correlation matrix for the `ads` data frame. Is there any redundancy in the data? Are there any features that aren't needed?

In [13]:
# Place your code here
ads.corr()
# yes, variable last_buy and last_visit are correlated at a high value, they are almost linear functional related,
# so there's data redundancy, and only one variable is needed which contains complete information

,isbuyer,buy_freq,visit_freq,buy_interval,sv_interval,expected_time_buy,expected_time_visit,last_buy,last_visit,multiple_buy,multiple_visit,uniq_urls,num_checkins,y_buy
isbuyer,1.000000,NaN,0.326373,0.253749,0.037496,-0.187782,-0.080492,-0.089678,-0.089678,0.379045,0.231174,-0.006641,-0.004424,0.112434
buy_freq,NaN,1.000000,0.487548,0.398839,0.000280,-0.291767,0.060817,-0.126793,-0.126793,0.735054,0.154837,0.042624,0.042764,0.128118
visit_freq,0.326373,0.487548,1.000000,0.262660,0.140983,-0.147219,-0.121919,-0.171388,-0.171388,0.354157,0.472163,0.039079,0.048881,0.118092
buy_interval,0.253749,0.398839,0.262660,1.000000,0.042134,0.005762,0.010266,-0.046015,-0.046015,0.669442,0.083427,0.013895,0.008804,0.068453
sv_interval,0.037496,0.000280,0.140983,0.042134,1.000000,0.001817,0.017179,-0.150368,-0.150368,0.022634,0.534310,0.094210,0.073020,0.011096
expected_time_buy,-0.187782,-0.291767,-0.147219,0.005762,0.001817,1.000000,0.053677,-0.001402,-0.001402,-0.495407,-0.059168,-0.008078,-0.005148,-0.038141
expected_time_visit,-0.080492,0.060817,-0.121919,0.010266,0.017179,0.053677,1.000000,-0.284973,-0.284973,-0.013129,-0.516888,-0.083879,-0.051314,0.011826
last_buy,-0.089678,-0.126793,-0.171388,-0.046015,-0.150368,-0.001402,-0.284973,1.000000,1.000000,-0.058602,-0.183995,0.268582,0.142725,-0.059171
last_visit,-0.089678,-0.126793,-0.171388,-0.046015,-0.150368,-0.001402,-0.284973,1.000000,1.000000,-0.058602,-0.183995,0.268582,0.142725,-0.059171
multiple_buy,0.379045,0.735054,0.354157,0.669442,0.022634,-0.495407,-0.013129,-0.058602,-0.058602,1.000000,0.123419,0.004246,0.005247,0.109926
multiple_visit,0.231174,0.154837,0.472163,0.083427,0.534310,-0.059168,-0.516888,-0.183995,-0.183995,0.123419,1.000000,0.043860,0.045599,0.070968
uniq_urls,-0.006641,0.042624,0.039079,0.013895,0.094210,-0.008078,-0.083879,0.268582,0.268582,0.004246,0.043860,1.000000,0.419581,-0.019238
num_checkins,-0.004424,0.042764,0.048881,0.008804,0.073020,-0.005148,-0.051314,0.142725,0.142725,0.005247,0.045599,0.419581,1.000000,-0.007766
y_buy,0.112434,0.128118,0.118092,0.068453,0.011096,-0.038141,0.011826,-0.059171,-0.059171,0.109926,0.070968,-0.019238,-0.007766,1.000000